server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包 com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1


mybatis:
  mapperLocations: classpath:mapper/*.xml # mapper接口位置
  type-aliases-package: com.atguigu.springcloud.entities    # 所有Entity别名类所在包
eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  # 集群版
  instance:
    instance-id: payment01 # 给实例取名称
    prefer-ip-address: true #引用ip地址
    # lease-expiration-duration-in-seconds: 1 # eureka最后一次心跳检测等待时间,超时就剔除
    # lease-renewal-interval-in-seconds: 2 # 发送心跳的间隔
    # Eureka客户端向服务端发送心跳的时间间隔，单位为秒(默认是30秒)
    # lease-renewal-interval-in-seconds: 1
    # Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒(默认是90秒)，超时将剔除服务
    # lease-expiration-duration-in-seconds: 2