server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_8001
          #uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE #协议使用springcloud提供的负载均衡，查询服务列表，采用轮询方式
          predicates:
            - Path=/payment/get/**
#            - Cookie=username,zhangsan
#            - Header=X-Requst-Id, \d+
#            - Host=test.com:8081
#            - Method=POST
#            - After=2022-05-06T16:01:25.629+08:00[Asia/Shanghai]

      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由功能，通过服务名称获取服务实现负载均衡
#          - id: payment_routh    #路由的ID，没有固定规则但要求唯一，建议配合服务名
#            uri: http://localhost:8001          #匹配后提供服务的路由地址
#            predicates:
#              - Path=/payment/get/**         # 断言，路径相匹配的进行路由
#
#          - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
#            uri: http://localhost:8001          #匹配后提供服务的路由地址
#            predicates:
#              - Path=/payment/lb/**         # 断言，路径相匹配的进行路由

eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka